[build]
  publish = "."
  command = "node inject-env.js"

[[redirects]]
  from = "/"
  to = "/glb-scene-editor-1024.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"
    Cache-Control = "public, max-age=31536000"